### ISSUE TITLE
Controller.php model loader (class not found)

### ISSUE THREAD

**Issue by Creeall** [OmarElGabry/miniPHP#9] opened 2016-05-18 21:32 UTC
There might be an issue with :
Controller.php

```
public function loadModel($model){
        return $this->{$model} = new $model();
}
```

I get **class not found** when validating login form and the class name the app is looking for is "login" instead of "Login" (the model class).

I made some change in the framwork to match my needs so it may as well be my own fault.
But just in case I think it's better to report this. So you can double check.

The fix for me was just to add the uc_words() to force an uppercase like this:

```
public function loadModel($model){
        $uc_model = ucwords($model);
        return $this->{$model} = new $uc_model();
}
```

And I get past the login form to the dashboard as expected now.

**Comment by OmarElgabry** [comment] 2016-05-19 04:43
I don't think the case sensitivity matters when you try to initialize a new instance. Take a look at the following code, It works just fine.

``` php
class classA {

    public function printmsg(){
        echo "hello A";
    }

    public function __get($model) {
        return $this->{$model} = new $model();
    }
}

class classB {

    public function printmsg(){
        echo "hello B";
    }
}

$foo = new cLAssA();
$foo->ClaSsb->printmsg();
```

**Comment by Creeall** [comment] 2016-05-19 18:35
Well all I can say is as soon as I remove my trick, I get : 

```
19/05/2016 18:18:48 | /Test/scripts/Controller.php | 240 | Error
Class 'user' not found
```

on basic index.php request.

And the step by step debugging leads me to this method (loadModel) of the main Controller class with the only difference being the character case of the call, and then crash 500.

It doesn't sound right to me either! But here I am, better report a possible false, environment dependent bug than doing nothing abou it :-)

Running php 7 atm.
It could be related to autoloading issues I created? I had to work around and avoid namespacing so made some changes (not using native composer way). But everything works just great with my fix.

By the way, thank you for this amazing piece of work ! It's a master piece for learning stuff when you're too weak to master big Frameworks and too hot to keep coding without them. A key piece in the learning curve.

**Comment by Creeall** [comment] 2016-05-19 19:05
I can also add that it seems to me that this kind of model call, using magic method is used a lot in other location in this framework without an issue.
Am I right ? lines like $this->controller->login->logout(...), $this->controller->randomModelName...
I'm totally lost on the singular  behavior in Controller.php.

**Comment by OmarElgabry** [comment] 2016-05-19 19:39
If you put your model classes elsewhere other than inside `app/models/`, your model class won't be loaded, because the autoloader will only load the classes inside `app/models/`. See [composer.json](https://github.com/OmarElGabry/miniPHP/blob/master/composer.json#L25).

**Comment by Creeall** [comment] 2016-05-19 19:49
Yeah I know. That's why I modified the autoloader classes myself to parse the right folders.
Location of the models isn't an issue here. 
Anyway, if this issue only happens for me. Don't worry and close the Issue.
Maybe I'll find the reason later.

**Comment by OmarElgabry** [comment] 2016-05-19 19:57
The problem is you are changing the default structure for the framework, and maybe you added some additional code there, or something else you've done that cause the problem. But, if you are using the framework without any modifications, it should work just fine, and I can help you with your problems. Because honestly, I can't figure out what actually causing the problem.

**Comment by Creeall** [comment] 2016-05-19 20:07
Yeah, no worry Omar, it's all good as I fixed my issue.
Just wanted to see if this was a real issue or just a side effect of my installation.
I have my answer.

**Comment by creative-coder** [comment] 2016-05-20 18:49
i had the same issue, on windows works just fine, but not under linux, i fixed it with the ucword method

**Comment by OmarElgabry** [comment] 2016-05-20 21:18
@Creeall @creative-coder Thank you for reporting. It's fixed now.

**Comment by Creeall** [comment] 2016-05-20 21:18
Right, I failed to mention I'm using OS X.
Good to know. Now I have to on windows, just to see if this happens to me too.

**Comment by OmarElGabry** [comment] 2016-06-08 20:53
Opps! Re-fixed The Controller Model Loader. I shouldn't modify `$model`, instead I had to use another variable i.e. `$uc_model`.

**Comment by creative-coder** [comment] 2016-06-09 06:00
The Model NewsFeed class was not found on linux because it does not find/load the class in PascalCase.

in NewsFeedController line 41
$this->user->clearNotifications(Session::getUserId(), $this->newsfeed->table);
if i change it to
$this->user->clearNotifications(Session::getUserId(), $this->NewsFeed->table);
its loaded perfect

**Comment by ghost** [comment] 2016-06-09 06:02
CamelCase you mean?!

Also nice to notice that issue, i've changed it also but forgot to report!

**Comment by creative-coder** [comment] 2016-06-09 06:17
upper camel case, a.k.a. PascalCase: ThisIsAnExample. thisIsNotAnExample.
lower camel case: thisIsAnExample. ThisIsNotAnExample.

**Comment by ghost** [comment] 2016-06-09 06:18
I understand CamelCase but didn't know that PascalCase is a alias! :)

**Comment by OmarElgabry** [comment] 2016-06-09 08:20
Uppercase First Letter used to load the model, while lowercase letters is used to trigger the model class in the controller(i.e. $this->model). It's fixed now again. Sorry for that.

**Closed as completed** 2016-06-15 18:08 UTC
